In [1]:
para='''Shakespeare was born and raised in Stratford-upon-Avon, Warwickshire. At the age of 18, he married Anne Hathaway, with whom he had three children: Susanna and twins Hamnet and Judith. Sometime between 1585 and 1592, he began a successful career in London as an actor, writer, and part-owner of a playing company called the Lord Chamberlain's Men, later known as the King's Men. At age 49 (around 1613), he appears to have retired to Stratford, where he died three years later. Few records of Shakespeare's private life survive; this has stimulated considerable speculation about such matters as his physical appearance, his sexuality, his religious beliefs, and whether the works attributed to him were written by others'''

In [2]:
import nltk

In [3]:
text=nltk.word_tokenize(para)

In [4]:
nltk.pos_tag(text)

[('Shakespeare', 'NNP'),
 ('was', 'VBD'),
 ('born', 'VBN'),
 ('and', 'CC'),
 ('raised', 'VBN'),
 ('in', 'IN'),
 ('Stratford-upon-Avon', 'NNP'),
 (',', ','),
 ('Warwickshire', 'NNP'),
 ('.', '.'),
 ('At', 'IN'),
 ('the', 'DT'),
 ('age', 'NN'),
 ('of', 'IN'),
 ('18', 'CD'),
 (',', ','),
 ('he', 'PRP'),
 ('married', 'VBD'),
 ('Anne', 'NNP'),
 ('Hathaway', 'NNP'),
 (',', ','),
 ('with', 'IN'),
 ('whom', 'WP'),
 ('he', 'PRP'),
 ('had', 'VBD'),
 ('three', 'CD'),
 ('children', 'NNS'),
 (':', ':'),
 ('Susanna', 'NNP'),
 ('and', 'CC'),
 ('twins', 'NNS'),
 ('Hamnet', 'NNP'),
 ('and', 'CC'),
 ('Judith', 'NNP'),
 ('.', '.'),
 ('Sometime', 'NNP'),
 ('between', 'IN'),
 ('1585', 'CD'),
 ('and', 'CC'),
 ('1592', 'CD'),
 (',', ','),
 ('he', 'PRP'),
 ('began', 'VBD'),
 ('a', 'DT'),
 ('successful', 'JJ'),
 ('career', 'NN'),
 ('in', 'IN'),
 ('London', 'NNP'),
 ('as', 'IN'),
 ('an', 'DT'),
 ('actor', 'NN'),
 (',', ','),
 ('writer', 'NN'),
 (',', ','),
 ('and', 'CC'),
 ('part-owner', 'NN'),
 ('of', 'IN'),
 ('a', 'DT'),
 ('playing', 'NN'),
 ('company', 'NN'),
 ('called', 'VBD'),
 ('the', 'DT'),
 ('Lord', 'NNP'),
 ('Chamberlain', 'NNP'),
 ("'s", 'POS'),
 ('Men', 'NNP'),
 (',', ','),
 ('later', 'RB'),
 ('known', 'VBN'),
 ('as', 'IN'),
 ('the', 'DT'),
 ('King', 'NNP'),
 ("'s", 'POS'),
 ('Men', 'NNP'),
 ('.', '.'),
 ('At', 'IN'),
 ('age', 'NN'),
 ('49', 'CD'),
 ('(', '('),
 ('around', 'IN'),
 ('1613', 'CD'),
 (')', ')'),
 (',', ','),
 ('he', 'PRP'),
 ('appears', 'VBZ'),
 ('to', 'TO'),
 ('have', 'VB'),
 ('retired', 'VBN'),
 ('to', 'TO'),
 ('Stratford', 'NNP'),
 (',', ','),
 ('where', 'WRB'),
 ('he', 'PRP'),
 ('died', 'VBD'),
 ('three', 'CD'),
 ('years', 'NNS'),
 ('later', 'RB'),
 ('.', '.'),
 ('Few', 'JJ'),
 ('records', 'NNS'),
 ('of', 'IN'),
 ('Shakespeare', 'NNP'),
 ("'s", 'POS'),
 ('private', 'JJ'),
 ('life', 'NN'),
 ('survive', 'VBP'),
 (';', ':'),
 ('this', 'DT'),
 ('has', 'VBZ'),
 ('stimulated', 'VBN'),
 ('considerable', 'JJ'),
 ('speculation', 'NN'),
 ('about', 'IN'),
 ('such', 'JJ'),
 ('matters', 'NNS'),
 ('as', 'IN'),
 ('his', 'PRP$'),
 ('physical', 'JJ'),
 ('appearance', 'NN'),
 (',', ','),
 ('his', 'PRP$'),
 ('sexuality', 'NN'),
 (',', ','),
 ('his', 'PRP$'),
 ('religious', 'JJ'),
 ('beliefs', 'NNS'),
 (',', ','),
 ('and', 'CC'),
 ('whether', 'IN'),
 ('the', 'DT'),
 ('works', 'NNS'),
 ('attributed', 'VBD'),
 ('to', 'TO'),
 ('him', 'PRP'),
 ('were', 'VBD'),
 ('written', 'VBN'),
 ('by', 'IN'),
 ('others', 'NNS')]